export const SET_BALANCE = 'SET_BALANCE';

export const SET_BALANCE_TWO = 'SET_BALANCE_TWO'

export const DEPOSIT_BALANCE = 'DEPOSIT_BALANCE'

export const WITHDRAW_BALANCE = 'WITHDRAW_BALANCE'

export const RESET_BALANCE = 'RESET_BALANCE'

export const FETCH_BITCOIN = 'FETCH_BITCOIN';
